### ISSUE TITLE
【业务组件】Exception 异常

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/test#10]
<img width="1081" alt="2017-07-20 3 18 53" src="https://user-images.githubusercontent.com/7017767/28406708-32565576-6d64-11e7-9b2f-8b1dba87bfd9.png">

[视觉稿](https://lark.alipay.com/ui-assets/bf3zoa#6388)

**使用方式**
	const actions = <Button>Go</Button>
	<Exception type="404" />
	<Exception title="出错啦！" desc="我也不知道为啥" img="img.png" actions={actions} />

**功能概要**

- 异常页面，默认支持 404，500 等场景，每个场景有默认图片，title，描述及跳转按钮，可修改

**API**

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|
| type       | 页面类型，若配置，则自带配套的 title，desc，img     | Enum{'404', '500', '503'}  | -    |
| title       | 标题     | ReactNode  | -    |
| desc       | 说明     | ReactNode  | -    |
| img       | 图片地址     | string  | -    |
| actions       | 建议操作，配置此属性时默认的『返回首页』按钮不生效    | ReactNode  | -    |

**Comment by nikogu** [comment]
建议 `type` 配置了，默认带 `button`，写个 `href` 连接就好了，如果有 `extra` 属性，则按照  `extra` 来，如何

**Comment by ddcat1115** [comment]
阔以，我改下

**Comment by afc163** [comment]
`ExceptionPage` => `Exception`

**Comment by ddcat1115** [comment]
https://github.com/ant-design/test/pull/35
