### ISSUE TITLE
【业务组件】Result 处理结果

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/test#11]
<img width="669" alt="2017-07-20 3 41 29" src="https://user-images.githubusercontent.com/7017767/28406853-a67d38de-6d64-11e7-9017-88eb64e61ae5.png">

[视觉稿](https://lark.alipay.com/ui-assets/bf3zoa/45574)

**使用方式**

```
const actions = <Button>Home</Button>
<Result type="success" title="申请成功" desc="运气真好！" actions={actions} />
```

**功能概要**

- 结果页面，支持 成功，警告，失败 三种场景，每个场景有默认顶部 Icon
**API**

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|
| type       | 页面类型     | Enum{'success', 'warning', 'error'}  | -    |
| title       | 标题     | ReactNode  | -    |
| desc       | 说明     | ReactNode  | -    |
| extra       | 补充信息，有默认的灰色背景     | ReactNode  | -    |
| actions       | 操作建议，推荐放置跳转链接等    | ReactNode  | -    |

**Comment by afc163** [comment]
直接叫 Result 好了。

**Comment by afc163** [comment]
desc => description

原则上不缩写。

**Comment by afc163** [comment]
<img width="854" alt="image" src="https://user-images.githubusercontent.com/507615/28862769-dfd75824-7798-11e7-998b-77053fc32383.png">

默认左右的 120px 是啥，不合理。

**Comment by ddcat1115** [comment]
已按最新视觉修改 https://github.com/ant-design/test/pull/58
