### ISSUE TITLE
【业务组件】MiniChartCard 迷你图表卡片

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/test#13]
<img width="222" alt="2017-07-21 9 16 56" src="https://user-images.githubusercontent.com/7017767/28445172-37c4c6e6-6df5-11e7-91f1-0661fc5cbfa4.png">

[交互](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=图表卡片)
[视觉](https://lark.alipay.com/ui-assets/bf3zoa/51515)

**Comment by nikogu** [comment]
`g2-react-pro`...

**Comment by afc163** [comment]
会类似：https://github.com/RaoHai/pretty-chart

**Comment by ddcat1115** [comment]
图表相关的还有个问题要确认，设计是那边希望用 pretty-chart 的样式，跟目前g2区别还蛮大的

**Comment by afc163** [comment]
以 default 版本的视觉稿为准即可。

**Comment by nikogu** [comment]
这一块我觉得有待商榷，如果图表样式需要规范样式，可以考虑 `g2-antd`，但是前提是设计师确实有图表这一块的设计沉淀，不是拍脑壳只是模仿别人搞的，要不然配的图表样式都是白用工

**Comment by afc163** [comment]
要列一下有哪些 type 。

另外，dashboard 页面最下面那个有可滚动标签的大图表可能需要单列，重型组件。

**Comment by nikogu** [comment]
今天上午仔细看了一下， `pretty-chart` 除了它自带的 `Row` 布局以外，跟我们视觉稿的图表差别很大啊，基本不可用，还不如直接基于 `g2` 来搞。

跟陆沉也沟通了一下，目前 `pretty-chart` 在持续维护，但是之前是跟 `小马姐`（who？视觉）一起做的，不过已经 2 个多月没更新了，我稍后跟视觉沟通下，这块到底是什么情况，从目前情况来看，我建议：

1. 自己在 `g2` 底层上做 `ant-design-pro-chart`
2. 找陆沉共建，改的还挺多，不知道有空没
3. 直接搞 `pretty-chart`，那工作量就大了

**Comment by afc163** [comment]
直接搞，不基于 pretty-chart 。

**Comment by afc163** [comment]
MiniChartCard => ChartCard

目标是实现中后台最常用的少数的图表卡片形式，对自定义需求保持有限开放，和 PrettyChart 并行发展。

**Comment by nikogu** [comment]
好的，已经跟设计确认，先不管 `PrettyChart`，将图表先抽离出来放到 `components/charts` 中。

感觉这个还是要分两种，一种是 卡片 的，一种不是，因为很多场景都是图表在卡片中组合。建议的实现方式可以结合 `PrettyChart` 的布局，免得重新又搞一套？：

```javascript
<DeerCard title="访问量" footer="日访问量 1,234">
    <Meta>
      <Meta.Item title="整行"> 8,846</Meta.Item>
    </Meta>
    
    <Meta>
        <MiniChartLine /> // 这个由我们实现
    </Meta>
    
  </DeerCard>
```

**Comment by afc163** [comment]
粒度太细了，直接：

```
<ChartCard>
</ChartCard>
```

不去做图表组件。这样业务替换起来方便很多，对各种自定义需求也不予支持。

**Comment by nikogu** [comment]
我们对外的，给用户的，是 `<ChartCard />`，但是 `<ChartCard />` 里面是  `PrettyChart 布局` + 自定义图表

**Comment by nikogu** [comment]
发现我想多了，`PrettyChart` 的布局也不一样，算了算了，自己搞吧

**Comment by nikogu** [comment]
https://github.com/ant-design/test/tree/master/scaffold/src/components/Charts
