### ISSUE TITLE
开发流程增强

### ISSUE THREAD

**Issue by afc163** [ant-design/test#2]
目前问题：

- [x] `npm run install-other` 和 `npm run install-start` 都整合的 postinstall 逻辑中，不对开发者暴露。
- [x] 优先使用 tnpm 。
- [x] `npm start` 后有报错信息。
   ```
   ERROR in ./~/_bisheng@0.24.2@bisheng/lib/loaders/source-loader.js!./components/src/sample/demo/basic.md
   [0] Module not found: Error: Cannot resolve 'file' or 'directory' /Users/afc163/Projects/ant-design-admin/components in /Users/afc163/Projects/ant-design-admin/components/src/sample/demo
   [0]  @ ./~/_bisheng@0.24.2@bisheng/lib/loaders/source-loader.js!./components/src/sample/demo/basic.md 66:17-36
   ```
- [x] 业务组件目录是在 scaffold 目录中，组件不单独维护。

## 功能支持

- [x] 添加 precommit 和 lint-staged 支持。
- [x] 添加 travis ci。
- [x] 脚手架部署一个演示站点，方便设计师随时查看。

**Comment by nikogu** [comment]
> 业务组件目录是在 scaffold 目录中，组件不单独维护

这个的意思是直接像业务组件一样写在 scaffold 里？那需要发布部署吗，脚手架里面使用不走 npm 吗，这个好像跟规划的不一样

**Comment by afc163** [comment]
是一样的，业务组件写在 scaffold，被脚手架的代码直接使用。但是同时又可以调试和对外发布。

**Comment by nikogu** [comment]
这样有点问题，脚手架里面使用 antd pro 组件应该是标准化的吧，就像其它规范业务一样，如果跟业务组件混在一起，变成了代码源有些混乱，而且想不到有什么好处，改了还容易跟 npm 不一致

**Comment by nikogu** [comment]
这样有点问题，脚手架里面使用 antd pro 组件应该是标准化的吧，就像其它规范业务一样，如果跟业务组件混在一起，变成了代码源有些混乱，而且想不到有什么好处，改了还容易跟 npm 不一致

**Comment by nikogu** [comment]
组件应该还有配套的文档和 demo 也都混在一起了

**Comment by afc163** [comment]
混在一起没关系，以脚手架方式使用的，代码直接进项目方便二次修改。antd pro 组件本身不是非常严格的组件，算是业务开发中方便复用的一些代码。业务中改造和变化的可能性会比较大，文档和演示什么的质量也并非会像 antd 要求的那么高。另外，提炼成 npm 模块是方便一些已有的项目进行使用。

**Comment by nikogu** [comment]
我觉得 scaffold 应该是一个精品，里面的使用都是规范标准的，并且我觉得 pro 的定位也应该是一个独立完整的产品。

当下从脚手架的层面入手，根据业务的改造和变化来写业务组件我是认同的，不过我觉得最好一开始留个坑，所以感觉 pro 的 components 一开始抽离 scaffold 是更好的，在组件标准上我建议对标 ant.design。

然后为了解决下载脚手架就是完整代码的需求，我建议可以目前可以 __直接把 components 平移到 scaffold，但是结构还是保持现在较为规范的结构，便于之后的独立__，并且也不影响现在二次修改的需要。

**Comment by afc163** [comment]
pro 和 scaffold 不是割裂的，是一个东西。

**Comment by afc163** [comment]
> 直接把 components 平移到 scaffold。

就是这个意思。

**Comment by afc163** [comment]
试试把现有的三个组件 publish 一下，顺便把 npm 坑位占了。

**Comment by nikogu** [comment]
已经 publish 了，不过打包的内容有点问题，我再调调

**Comment by waybi** [comment]
请问怎么单独发 npm，我看ant-design-pro的npm包是把组件打包到lib文件夹下，这个过程是怎么处理的？

**Comment by nikogu** [comment]
@waybi 看这个：https://github.com/ant-design/ant-design-pro-site/tree/master/config/components
