### ISSUE TITLE
components 发布优化

### ISSUE THREAD

**Issue by nikogu** [ant-design/test#20]
- [x] package.json 不增加机器写入的 `dependencies` 依赖，保持人为纯净
- [x] 增加 localIdentName 支持，[详见](https://github.com/webpack-contrib/css-loader#modules)
- [x] <del>完善 `/tool/bin/i`，使得根据用户运行的命令来选择 `npm` 版本，而不用 `try catch` 判断</del> `未找到实现方案`

**Comment by afc163** [comment]
这个搞完把组件先发了？

**Comment by nikogu** [comment]
这个我明天搞下。。。今天还没抽出空

**Comment by nikogu** [comment]
https://github.com/ant-design/test/commit/56a51dedc2f52ed3179b12129b444f54967b9b6a
