### ISSUE TITLE
业务组件讨论：卡片变形（Card 衍生模板）

### ISSUE THREAD

**Issue by nikogu** [ant-design/test#23]
![image](https://user-images.githubusercontent.com/1179603/28560088-d9618efe-714b-11e7-94aa-bcb0301db39f.png)

![image](https://user-images.githubusercontent.com/1179603/28560099-df421d20-714b-11e7-8bd5-6edda3f55d72.png)

![image](https://user-images.githubusercontent.com/1179603/28560103-e5a08d0a-714b-11e7-827f-44b840d56af9.png)

问题：如果每次都按照各自的样式写，有些繁琐，但是这种卡片业务属性很重，重用度是个问题，写的太灵活又省不了多少事，写的太死板又不好扩展。

方案：打算实现一个 `CardPro`，内置这几套模板，然后通过 `mode`（或者 `theme` ） 参数来进行切换，用户使用只需要传入数据即可，然后提供几个 `hook`：`extraContent` 、`extraFooter`、`extraHeader`，可以自己自定义部分，但是大体布局还是跟原有模板保持一致。

@ddcat1115 @afc163 看看是否可行

**Comment by afc163** [comment]
antd Card 组件要增强，按照之前和设计师的讨论，添加如下属性：

- cover
- actions

```
<Card
  cover={<img src="xxxx" />}
  actions={[<Icon type="xx" />, <Icon type="xx" />, <Icon type="xx" />]}
/>
```

ref #3

**Comment by nikogu** [comment]
好的，那应该会好很多，不过 `content` 可能还是要写很多代码，可以先按照 `模板` 来实现，如果设计交互足够抽象了，再提取业务组件。

**Comment by afc163** [comment]
进一步，封装度更高的。添加以下属性：

```diff
<Card
  cover={<img src="xxxx" />}
  actions={[<Icon type="xx" />, <Icon type="xx" />, <Icon type="xx" />]}
+ title="title"
+ avatar="<Avatar src="xxxx" />"
+ description="description"
+ extraContent={<div>xxxx</div>}
/>
```

**Comment by afc163** [comment]
@ddcat1115 关注下，底层的 List 和 Card 可以先行搞掉。

**Comment by ddcat1115** [comment]
有 children 时，`cover` 和 `actions` 也应该被覆盖吧，原因：

- children 和 `cover` 的位置关系不要说清楚
- `actions` 在有 children 的 Card 里的功能就是 `extra`，如果提供两个会比较困扰，且从设计上来讲，也不会出现同时有顶部 `title` 和 `actions` 的情况

实际上，改良后的 Card 完全分为两条线，一种用 children，是完全自定义内容的路子，一种用新增的这些属性，是我们提供的捷径，觉得两个方向尽量不要有重叠比较好，甚至捷径这条路的标题都可以不叫 `title`，比如 `caption` ?

**Comment by afc163** [comment]
不覆盖。

正常顺序：标题栏 + cover + children + actions
如果指定了 children，avatar description extraContent 则无效。

**Comment by afc163** [comment]
https://v4-alpha.getbootstrap.com/components/card/

**Comment by nikogu** [comment]
https://github.com/ant-design/ant-design/pull/7087

**Comment by benjycui** [comment]
这种和金融云的卡片又是什么关系。。

See 内网 react-ui/ant-design-enterprise/issues/144

**Comment by nikogu** [comment]
我的理解是，金融云的卡片以后可以用新卡片的样式了吧，之前卡片样式没有，就自己设计了，现在有了差不多有点像的，可以直接用了。

> 可能这次卡片的部分样式也是从金融云卡片抽离出来的？

**Comment by benjycui** [comment]
> 我的理解是，金融云的卡片以后可以用新卡片的样式了吧，之前卡片样式没有，就自己设计了，现在有了差不多有点像的，可以直接用了。

最好能统一，但是这个你要找 钟欣 确认下。

**Comment by afc163** [comment]
目前这个会是标准版本。
