### ISSUE TITLE
【8.10】开发进度

### ISSUE THREAD

**Issue by nikogu** [ant-design/test#26]
#### 页面
- [x] 布局 @afc163 
- [ ] Dashboard @nikogu 
    - [x] 分析页 `0804` https://github.com/ant-design/test/pull/39
    - [ ] 监控页（两个图表待跟图形组沟通） `0804` https://github.com/ant-design/test/pull/39
    - [x] 工作台 `0804` https://github.com/ant-design/test/pull/39
- [x] 列表页 @nikogu 
    - [x] 标准表格（表格查询） `reviewing`
    - [x] 标准列表 `0809`
    - [x] 卡片列表 `0809`
    - [x] 卡片列表（封面）`0809`
    - [x] 搜索列表 `0809`
- [x] 表单页 @afc163 
    - [x] 基础表单 `08-01` #34
    - [x] 分步表单 `08-04` #37
    - [x] 长表单 `08-10`
    - [x] 分组表单 `08-10`
- [x] 详情页 @ddcat1115  `08-10`
- [x] 账户 @ddcat1115 
    - [x] 登陆 `08-04`
    - [x] 注册 `08-04`
- [x] 结果 @ddcat1115 
    - [x] 成功 `08-02`
    - [x] 失败 `08-02`
    - ~~[ ] 处理中 `08-02`~~
- [x] 错误 @ddcat1115 
    - [x] 403 `08-02`
    - [x] 404 `08-02`
    - [x] 500 `08-02`

#### 业务组件 https://github.com/ant-design/test/issues
- [ ] GlobalHeader
- [x] GlobalFooter
- [x] DescriptionList
- [x] MiniChartCard
- [x] ~~SidePanel~~
- [x] Result
- [x] Exception
- [x] PageHeader
- [x] FooterToolBar
- [ ] GlobalSearch
- [ ] NoticePopover
- [x] Chart

**Comment by afc163** [comment]
👍
