### ISSUE TITLE
Improve lint

### ISSUE THREAD

**Issue by afc163** [ant-design/test#27]
- [x] stylelint for less code
- [x] eslint-plugin-markdown
- [x] check the lint rules: https://github.com/ant-design/test/pull/25#discussion_r129527173

**Comment by nikogu** [comment]
https://github.com/ant-design/test/pull/25#discussion_r129527173

这个 rule 找了半天没找到，偏右君，有空看看

**Comment by afc163** [comment]
https://github.com/airbnb/javascript/blob/a206c52854ec8de387289ceb3d88fefc7ff2b030/packages/eslint-config-airbnb/rules/react.js#L58

确实不是错误，忽视吧。
