### ISSUE TITLE
【业务组件】NoticeIcon 消息提示

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/test#5]
<img width="414" alt="2017-07-19 7 50 53" src="https://user-images.githubusercontent.com/7017767/28366199-44a112ee-6cbe-11e7-8868-c7323939e9d7.png">

[视觉稿](https://lark.alipay.com/ui-assets/leu0s4/55643)
[交互](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=侧边导航)

**使用方式**

	const content = ...
	<NoticeIcon count={7} content={content} />

**功能概要**

- 放在全局导航中，用来提示消息或待办事项等，是对 `Popover` `Icon` `Badge` 的组装
- 有默认 Icon，可配置
- 带 badge（数字和红点两种）
- hover | click | focus 出现弹框
- 通知内容通过 ReactNode 配置，自带『无数据』效果
- 自带『清空』按钮，点击有回调，并呈现『无数据』效果

**API**

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|
| icon       | 展示的 Icon   | ReactNode     | `<Icon type="bell" />`    |
| count      | 消息条数      | number         | -      |
| dot        | 是否带点状 badge   | boolean     | false   |
| trigger    | 触发方式     | Enum{'hover', 'focus', 'click'}     | `hover`   |
| content    | 内容        | ReactNode     | `null`   |
| onClear    | 点击清空的回调        | function     | -   |
| onVisibleChange | 弹框显示隐藏的回调   | (visible) => void | - |

**Comment by nikogu** [comment]
感觉名字应该叫 `NoticePopover`

**Comment by ddcat1115** [comment]
好像是哦。。。我改下

**Comment by afc163** [comment]
想办法把 Tabs 和各自的 List 也内建，不然还是要写好多东西。

**Comment by afc163** [comment]
```jsx
<NoticePopover
  icon="bell"
  count={10}
>
  <NoticePopover.Tab list={[ ... ]} loading={loading}>通知（4）</NoticePopover.Tab>
  <NoticePopover.Tab list={[ ... ]} loading={loading}>消息（4）</NoticePopover.Tab>
  <NoticePopover.Tab list={[ ... ]} loading={loading}>待办（4）</NoticePopover.Tab>
</NoticePopover>
```
