### ISSUE TITLE
惨无人道的互查手册-【ddcat1115篇】

### ISSUE THREAD

**Issue by nikogu** [ant-design/test#54]
概要：https://github.com/ant-design/test/issues/48

#### 登录页

页面 | 分类 | 代码地址 | 问题描述 | 截图 | 改动建议 | 已修复 | 确认修复
---|---|---|---|---|---|---|---
[登陆页](http://localhost:8000/#/user/login) | 视觉还原  | - | 页面高度缩小，背景样式异常  | [截图](https://user-images.githubusercontent.com/1179603/29299863-3b8bd888-81a4-11e7-9761-2882fd7bfd3c.png) | 建议设置最小高度 | ✅  | [ 💯 ]
[登陆页](http://localhost:8000/#/user/login) | 视觉还原  | - | 需要有 hover 手型  | [截图](https://user-images.githubusercontent.com/1179603/29299948-d68761ea-81a4-11e7-9dc2-5ad09198df32.png) | cursor:pointer; | ✅  | [💯]
[登陆页](http://localhost:8000/#/user/login) | 视觉还原  | - | input 高度为 40px  | [截图](https://user-images.githubusercontent.com/1179603/29299993-32e7fd32-81a5-11e7-95ae-3b2246bbfbf8.png) | 需要覆盖 antd 样式（还是要升级？） | `已确认antd会升级样式，升级后大号input高度为40px，此处保持大号配置即可` | [💯]
[登陆页](http://localhost:8000/#/user/login) | 视觉还原  | - | 文本和 Radio 上下未居中对齐  | [截图](https://user-images.githubusercontent.com/1179603/29300033-701b5ef6-81a5-11e7-8ab7-1f8f2f1c4465.png) | - | `目前未对齐是因为仅仅简单调了文案字号，待 checkbox 整体升级后会fix` | [💯]
[登陆页](http://localhost:8000/#/user/login) | 视觉还原  | - | 上下间距为 48px 实际为 32px  | [截图](https://user-images.githubusercontent.com/1179603/29300077-bfacb19a-81a5-11e7-8163-7d1d98978f82.png) | 因为有实际的 tab 高度，所以实际高度应该是 42px 左右 | ✅  `改为了40px（加上tab 的上边距 8px = 48px）` | [💯]
[登陆页](http://localhost:8000/#/user/login) | 视觉还原  | - | logo 大小为整 40x40  | [截图](https://user-images.githubusercontent.com/1179603/29300148-4ee358aa-81a6-11e7-843a-6ecf8ef1c123.png) | - | ✅ `实际为44px` | [💯]
[登陆页](http://localhost:8000/#/user/login) | 视觉还原  | - | button 高度为 40px  | [截图](https://user-images.githubusercontent.com/1179603/29300259-fe293f0a-81a6-11e7-8fbb-8e1db60f9804.png) | - | `已确认antd会升级样式，升级后大号 Button 高度为40px，此处不用处理`| [💯]
[登陆页](http://localhost:8000/#/user/login) | 模板内容  | - | 缺少页面底部  | [截图](https://user-images.githubusercontent.com/1179603/29300181-835393c0-81a6-11e7-84c2-ae1e86510c8c.png) | - | ✅  | [💯]
[登陆页](http://localhost:8000/#/user/login) | 模板内容  | - | 高度 40px 同上 | [截图](https://user-images.githubusercontent.com/1179603/29300308-3ecdb2a2-81a7-11e7-8b3b-7b3a1af3a222.png) | - | `antd 统一升级，不用处理` | [💯]
[登陆页](http://localhost:8000/#/user/login) | 其它  | - | 用小写 s 更合理 | [截图](https://user-images.githubusercontent.com/1179603/29300340-67308cb0-81a7-11e7-8680-71d2c3df87f2.png) | - | ✅  | [💯]
[登陆页](http://localhost:8000/#/user/login) | 其它  | - | 可增加 mock 数据，使得流程更为顺畅，可以从登录页进入到首页 | - | - | `目前账号 tab 用来展现后台报错样式，手机 tab 随意输入都可以登录跳转至首页` | [💯]

#### 注册页

页面 | 分类 | 代码地址 | 问题描述 | 截图 | 改动建议 | 已修复 | 确认修复
---|---|---|---|---|---|---|---
[注册页](http://localhost:8000/#/user/register) | 视觉还原  | - | 高度 40px 同登录页 | - | - | `antd 统一升级，不用处理` | [💯]
[注册页](http://localhost:8000/#/user/register) | 视觉还原  | - | 背景颜色不符 | [截图](https://user-images.githubusercontent.com/1179603/29300584-ca4a10b8-81a8-11e7-88dc-f04d3e8c918d.png) | - | ✅  | [💯]
[注册页](http://localhost:8000/#/user/register) | 其它 | - | 小 s | [截图](https://user-images.githubusercontent.com/1179603/29300629-31e2c3e6-81a9-11e7-841c-8462e5ba7874.png) | - | ✅  | [💯]
[注册页](http://localhost:8000/#/user/register) | 视觉还原 | - | 验证反馈与视觉稿不一致 | [截图](https://user-images.githubusercontent.com/1179603/29300664-625d446a-81a9-11e7-87b5-6aad92bb582b.png) | - | ✅  | [💯]

#### 注册结果页

页面 | 分类 | 代码地址 | 问题描述 | 截图 | 改动建议 | 已修复 | 确认修复
---|---|---|---|---|---|---|---
[注册结果页](http://localhost:8000/#/user/register-result) | 视觉还原  | - | 下间距应为 32px 实际 24px | [截图](https://user-images.githubusercontent.com/1179603/29300737-f88ac6b0-81a9-11e7-8784-fe7ff5a64328.png) | - | `已按照最新视觉稿修改` [结果页](https://lark.alipay.com/ui-assets/bf3zoa#8195) | [💯]
[注册结果页](http://localhost:8000/#/user/register-result) | 视觉还原  | - | 行高、字体、下间距不符合视觉稿 | [截图](https://user-images.githubusercontent.com/1179603/29300767-2378c1b0-81aa-11e7-9c9e-60bbf2453344.png) | - | 已按照最新视觉稿修改` [结果页](https://lark.alipay.com/ui-assets/bf3zoa#8195) | [💯]
[注册结果页](http://localhost:8000/#/user/register-result) | 视觉还原  | - | 行高应为 24px 实际 21px，下间距应为 40px | [截图](https://user-images.githubusercontent.com/1179603/29300784-4697b41c-81aa-11e7-81b1-dd0d9b525370.png) | - | `已按照最新视觉稿修改` [结果页](https://lark.alipay.com/ui-assets/bf3zoa#8195) | [💯]
[注册结果页](http://localhost:8000/#/user/register-result) | 模板内容  | - | 缺少页面 footer 和 最小高度，同登陆注册 | - | - | ✅  | [💯]

#### 结果成功 & 失败页

页面 | 分类 | 代码地址 | 问题描述 | 截图 | 改动建议 | 已修复 | 确认修复
---|---|---|---|---|---|---|---
[结果成功页](http://127.0.0.1:8000/#/result/success) | 视觉还原  | - | 下间距应为 32px 实际 24px | [截图](https://user-images.githubusercontent.com/1179603/29300737-f88ac6b0-81a9-11e7-8784-fe7ff5a64328.png) | - | `已按照最新视觉稿修改` [结果页](https://lark.alipay.com/ui-assets/bf3zoa#8195)  | [💯]
[结果成功页](http://127.0.0.1:8000/#/result/success) | 视觉还原  | - | 下间距应为 16px 实际 8px | [截图](https://user-images.githubusercontent.com/1179603/29300918-43ec5eba-81ab-11e7-963a-5c59b74172ed.png) | 建议元素行高跟视觉稿保持一致，这样间距就较为准确 | `已按照最新视觉稿修改` [结果页](https://lark.alipay.com/ui-assets/bf3zoa#8195)  | [💯]
[结果成功页](http://127.0.0.1:8000/#/result/success) | 视觉还原  | - | 行高应为 22px 实际 21px | [截图](https://user-images.githubusercontent.com/1179603/29300941-7720364e-81ab-11e7-8864-29113d942fc3.png) | - | `antd 规范为行高1.5，这里只相差1px，感觉不用特殊覆盖`  | [💯]
[结果成功页](http://127.0.0.1:8000/#/result/success) | 视觉还原  | - | icon 与文本间距应为 8px | [截图](https://user-images.githubusercontent.com/1179603/29301014-d5f1e122-81ab-11e7-8cd2-fec0ac278af4.png) | - | ✅  | [💯]
[结果成功页](http://127.0.0.1:8000/#/result/success) | 视觉还原  | - | icon 与文本间距应为 8px | [截图](https://user-images.githubusercontent.com/1179603/29301014-d5f1e122-81ab-11e7-8cd2-fec0ac278af4.png) | - | ✅ | [💯]
[结果成功页](http://127.0.0.1:8000/#/result/success) | 视觉还原  | - | 上下间距应为 4px | [截图](https://user-images.githubusercontent.com/1179603/29301037-ff32feea-81ab-11e7-9536-b1e618c863b2.png) | - | ✅ | [💯]
[结果失败页](http://127.0.0.1:8000/#/result/success) | 视觉还原  | - |  icon 与视觉稿不符合 | [截图](https://user-images.githubusercontent.com/1179603/29301119-96109638-81ac-11e7-9843-1537a841b079.png) | - | ✅ | [💯]

#### 异常页面

页面 | 分类 | 代码地址 | 问题描述 | 截图 | 改动建议 | 已修复 | 确认修复
---|---|---|---|---|---|---|---
[异常页面](http://127.0.0.1:8000/#/result/success) | 视觉还原  | - | 没有居中 | - | 文本+图片是一个整体，应该整体居中，目前比例是文字定宽，左边自适应 | `这里跟设计师确认了一下，保持文案部分占右边9个栅格（37.5%）的宽度，已调整` | [💯]

#### 详情页

页面 | 分类 | 代码地址 | 问题描述 | 截图 | 改动建议 | 已修复 | 确认修复
---|---|---|---|---|---|---|---
[详情页](http://localhost:8000/#/profile) | 视觉还原  | - | 视觉稿是三列 | [截图](https://user-images.githubusercontent.com/1179603/29304388-46b41e0c-81c5-11e7-9b55-e4d2b3f9e5e9.png) | - | `这里信息太多，放三列的话每一列都很挤，跟海纳确认了下就放两列` | [💯]
[详情页](http://localhost:8000/#/profile) | 视觉还原  | - | 左对齐？ | [截图](https://user-images.githubusercontent.com/1179603/29304506-ee70b326-81c5-11e7-81f9-686ceca1b3a1.png) |  | `右边的列是右对齐的，可以参考『模块』里 PageHeader 的设计，视觉产出和模块产出相矛盾时以模块产出为准` [模块-PageHeader](https://lark.alipay.com/ui-assets/leu0s4/61879) | [💯]
[详情页](http://localhost:8000/#/profile) | 视觉还原  | - | 上下间距不对 | [截图](https://user-images.githubusercontent.com/1179603/29304571-5706e964-81c6-11e7-987a-7d93efa44288.png) |  | ✅ | [💯]
[详情页](http://localhost:8000/#/profile) | 视觉还原  | - | 响应式需要优化 | [截图](https://user-images.githubusercontent.com/1179603/29304680-e1e88a6a-81c6-11e7-8528-1231d6942022.png) |  | ✅ | [💯]
[详情页](http://localhost:8000/#/profile) | 视觉还原  | - | 横向间距跟视觉稿样式不一致 | [截图](https://user-images.githubusercontent.com/1179603/29304762-681eeade-81c7-11e7-8410-3a0ac2d11da8.png) |  | ✅ | [💯]
[详情页](http://localhost:8000/#/profile) | 视觉还原  | - | 对齐方式与视觉稿不一致 | [截图](https://user-images.githubusercontent.com/1179603/29304784-8daa6ed6-81c7-11e7-829e-90a153fdecfc.png) |  | `这里的页面视觉稿应该是老的，以最新的模块视觉稿为准` [描述列表-模块](https://lark.alipay.com/ui-assets/leu0s4/63895) | [💯]
[详情页](http://localhost:8000/#/profile) | 视觉还原  | - | 颜色与设计稿不一致 | [截图](https://user-images.githubusercontent.com/1179603/29304814-c284410e-81c7-11e7-981e-8a862a685ee9.png) |  | ✅ | [💯]
[详情页](http://localhost:8000/#/profile) | 视觉还原  | - | 高度与设计稿不一致 | [截图](https://user-images.githubusercontent.com/1179603/29304852-f5324e16-81c7-11e7-9773-f04fe0563f53.png) |  | ✅ | [💯]
[详情页](http://localhost:8000/#/profile) | 视觉还原  | - | 上下间距与设计稿不一致 | [截图](https://user-images.githubusercontent.com/1179603/29304870-1ee3aa20-81c8-11e7-9374-4a80f215de2e.png) |  | `Card 统一升级` | [💯]
[详情页](http://localhost:8000/#/profile) | 模板内容  | - | 缺少搜索框 | [截图](https://user-images.githubusercontent.com/1179603/29304885-3f0092b4-81c8-11e7-8580-a693c16810b1.png) |  | `技术无法实现，且『实时搜索』用在table里并不是很合适，已跟海纳沟通，会另外增加『实时搜索』的范例` | [💯]
[详情页](http://localhost:8000/#/profile) | 视觉还原  | [代码](https://github.com/ant-design/test/blob/727a07b361576321df92dbf982af3c99347b0b4b/scaffold/src/routes/User/Login.js#L172) | 使用 decorater `@Form.create` | - | - | ✅ | [💯]

**Comment by nikogu** [comment]
https://github.com/ant-design/test/pull/50

**Comment by nikogu** [comment]
#### 代码优化

https://github.com/ant-design/test/blob/548597f0b4a0fc6219fd7aa660a6ec52745e8352/scaffold/src/components/Result/index.js#L8

更简洁？

```jsx
  const iconMap = {
    error: <Icon className={styles.error} type="close-circle" />,
    success: <Icon className={styles.success} type="check-circle" />,
  };
  const clsString = classNames(styles.result, className);
  return (
    <div className={clsString} {...restProps}>
      <div className={styles.icon}>{iconMap[type]}</div>
      <div className={styles.title}>{title}</div>
      {description && <div className={styles.description}>{description}</div>}
      {extra && <div className={styles.extra}>{extra}</div>}
      {actions && <div className={styles.actions}>{actions}</div>}
    </div>
  );
```

**Comment by ddcat1115** [comment]
> 命名感觉可优化，比如：headerExtraInfoXXX，具有一定特点的？（此项只是讨论）

这里 . textSecondary 只是指定了颜色，使用它的元素没有什么功能上的共性，所以没有用有意义的命名

**Comment by nikogu** [comment]
验证完毕，还有部分等待 antd 升级的样式后续需要更新...眼睛已瞎 🏎

**Comment by afc163** [comment]
打个 ✅ 或 💯 吧。。
