### ISSUE TITLE
pro-cli

### ISSUE THREAD

**Issue by afc163** [ant-design/test#60]
有没有需求和可能统一搞一个命令行工具，类似 `ember-cli` `vue-cli` `angular-cli`。

```
$ pro start
$ pro e2e
$ pro mock /api/xxx
$ pro new-page xxx --type basic-form
$ pro new-page xxx --type 404
$ pro new-model xxx
```

**Comment by nikogu** [comment]
感觉可以有，下周搞一个

**Comment by afc163** [comment]
先想清楚需求边界。

**Comment by afc163** [comment]
不急，先把 List 组件搞完美。

**Comment by afc163** [comment]
https://github.com/hexagonframework/antd-admin-cli

**Comment by nikogu** [comment]
感觉这里的页面应该不是我们 `scaffold` 里面的页面，也许只是一个只有 UI 占位的简化版？如果包含逻辑还需要引入 `modal` `components` `utils` 等，感觉对于使用者来说一大堆东西更为复杂，是否定位成简化的『起步模板』？只是用于一个参考作用

**Comment by afc163** [comment]
对，会有空页面（已加，这个最常用）。一些标准页面也要有，方便快速生成原型。

**Comment by afc163** [comment]
另外可能需要封装类似 react-scripts 的 pro-scripts，用于满足升级脚手架的需求。

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#updating-to-new-releases

**Comment by afc163** [comment]
挺好的，只不过我们是开源方案。

**Comment by afc163** [comment]
pro-scripts 和  pro-cli 可以作为同一个东西。

**Comment by afc163** [comment]
到时候 bigfish 里应该需要加一篇 `如何在 bigfish 里使用 pro`。

**Comment by nikogu** [comment]
https://github.com/ant-design/test2-cli
