### ISSUE TITLE
UI Test 方案

### ISSUE THREAD

**Issue by afc163** [ant-design/test#63]
- https://macacajs.github.io/pageuitest
- https://github.com/macacajs/torchjs

**Comment by xudafeng** [comment]
🆗

**Comment by xudafeng** [comment]
https://github.com/macaca-sample/antd-sample

**Comment by afc163** [comment]
wait for https://github.com/macaca-sample/antd-sample

**Comment by xudafeng** [comment]
@afc163 

https://github.com/macaca-sample/antd-sample/blob/master/package.json#L54-L55

**Comment by afc163** [comment]
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#running-tests

**Comment by xudafeng** [comment]
https://github.com/macaca-sample/react-sample
