### ISSUE TITLE
业务组件引用方式修改

### ISSUE THREAD

**Issue by afc163** [ant-design/test#66]
```diff
- import { Xxx } from 'ant-design-pro';
+ import Xxx from 'ant-design-pro/Xxx';
```

- [ ] 发布目录修改。
- [ ] Demo 写法修改。

**Comment by nikogu** [comment]
弱弱的问下，这种写法有什么好处

**Comment by afc163** [comment]
按需使用，省体积。

**Comment by nikogu** [comment]
哦，酱紫，我还以为两个是一样的。

**Comment by afc163** [comment]
前一个会引入所有模块。

**Comment by nikogu** [comment]
@afc163 发布目录修改指的是？

**Comment by nikogu** [comment]
`import Xxx from 'ant-design-pro/lib/Xxx';` 这个直接这样不就好了

**Comment by afc163** [comment]
也行，我是想 main 文件就不暴露了，把组件文档里的写法也改改。

**Comment by nikogu** [comment]
https://github.com/ant-design/test/commit/0cd358867880dfec25a3c22a2806f92d58779e00
