### ISSUE TITLE
Move stylelint to test2

### ISSUE THREAD

**Issue by afc163** [ant-design/test#69]

**Comment by nikogu** [comment]
https://github.com/ant-design/test2/commit/5349737cd10fd2002fa0a99a347eedcfbb39915f

**Comment by afc163** [comment]
?

**Comment by afc163** [comment]
应该是这个 https://github.com/ant-design/test2/commit/315b660b4dd75a5cd08959d190fe6ad6cbbea90a

**Comment by afc163** [comment]
test 里的相关代码也移除掉吧。
