### ISSUE TITLE
【业务组件】PageHeader 页头

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/test#8]
<img width="935" alt="2017-07-19 7 55 07" src="https://user-images.githubusercontent.com/7017767/28366258-835b71c8-6cbe-11e7-9530-b69006440a2b.png">

[视觉稿](https://lark.alipay.com/ui-assets/leu0s4/54196)
[交互说明](http://axure.alibaba-inc.com/lark/596db13ef3dd6ed9cc19fb46/index#g=1&p=页头)

**使用方式**

```
const logo = <Icon type="home" />
const action = <Button>agree</Button>
const tabList = [
	{key: 'tab1', tab: 'tab1 title'}, 
	{key: 'tab2', tab: 'tab2 title'},
	{key: 'tab3', tab: 'tab3 title'},
]

<PageHeader title="标题" logo={logo} action={action} content="content" extraContent="extra">
	<PageHeader.Breadcrumb routes=... params=...  />
	<PageHeader.Tabs tabList={tabList} onChange=... />
</PageHeader>
```

**功能概要**

- 静态容器，包含页头部分的固定结构 ↓

<img width="932" alt="pageheader" src="https://user-images.githubusercontent.com/7017767/28581619-3ef587ae-7195-11e7-965a-f54b022011f7.png">

**API**

`PageHeader`

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|
| title       | title 区域   | ReactNode     | -    |
| logo       | logo区域，也可用来放返回按钮   | ReactNode     | -    |
| action       | 操作区，位于 title 行的行尾   | ReactNode     | -    |
| content       | 内容区   | ReactNode     | -    |
| extraContent       | 额外内容区，位于content的右侧   | ReactNode     | -    |

`PageHeader.Breadcrumb`

用法同 antd-Breadcrumb

`PageHeader.Tabs`

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|
| tabList       | tab 标题列表   | array<{key: string, tab: ReactNode}>     | -    |
| onChange  | 切换面板的回调   | (key) => void     | -    |

**Comment by nikogu** [comment]
我觉得这个组件（模板）如果离开了本身设计的基础，就基本上没有用了，比如：`nav` 这个，肯定得是 `breadcrumb`，要是变成一个其它的，那么没什么意义，所以这个组件主要靠模板。。。

`logo` 那个感觉可以去掉了，直接改成 < PageHeader back /> 好了，感觉没必要自定义

**Comment by ddcat1115** [comment]
这个组件的用处确实就是来规范视觉，没有什么功能性，我也纠结这种到底要不要抽成组件，还是只给模板就好了。。。

logo那块不一定是返回按钮，放什么不一定的

**Comment by afc163** [comment]
1. breadcrumb 要内建。
2. tabs 要内建。
3. extraContent 是 action 下面那块。

**Comment by ddcat1115** [comment]
已更新，还是略别扭。。。感觉这种纯粹为了规范样式做的容器，是不是更适合列出一系列符合规范的模板来解释？

**Comment by afc163** [comment]
tabsData 里面不会有 content。这里相当于：

```
<Tabs>
  <Pane title="xxx" />
  <Pane title="xxx" />
</Tabs>

**Comment by afc163** [comment]
1. 组件化会更方便复用。
2. 除了组件化之外，它的 demo 其实就是 `一系列符合规范的模板`。

**Comment by afc163** [comment]
- content 和 extraContent 是分开的，一个靠左一个靠右。

**Comment by ddcat1115** [comment]
https://github.com/ant-design/test/pull/25

**Comment by wulucxy** [comment]
这个 Tabs 和下面内容要怎么联动？有 demo 么
