### ISSUE TITLE
upgrade bisheng

### ISSUE THREAD

**Issue by nikogu** [ant-design/test#80]
https://github.com/ant-design/ant-design/pull/7985

- [ ] `root` 属性设置失效
- [ ] 打开站点闪一下报错

本地 ok、部署未报错，发到线上以后会出现上述两个问题。

**Comment by afc163** [comment]
:+1:

**Comment by nikogu** [comment]
https://github.com/ant-design/test/issues/79

**Comment by nikogu** [comment]
发布站点有点问题， @benjycui 已经在看了

**Comment by jljsj33** [comment]
挂了挂了

**Comment by benjycui** [comment]
> 打开站点闪一下报错

线上引了两份 react

https://github.com/ant-design/test/blob/596e4acf10fc9620e593e60bc20cb481c06b8282/site/bisheng.config.js#L38-L52

https://github.com/ant-design/test/blob/596e4acf10fc9620e593e60bc20cb481c06b8282/site/theme/static/template.html#L61

**Comment by nikogu** [comment]
好，我改改

**Comment by nikogu** [comment]
@benjycui 想起来了，这个地方其实是参考 antd 官网的：
https://github.com/ant-design/ant-design/blob/master/site/theme/static/template.html#L115
https://github.com/ant-design/ant-design/blob/master/site/bisheng.config.js#L70

这个地方有个问题是：
- 如果使用 `externals react`：bisheng build 会报错找不到 `ReactDOM`（应该是有依赖）
- 如果不 `externals react`：现在 `antd 3.0-alpha` 又有 `react 16` 的依赖，所以这样打包起来也会报有两个 `react` 的问题

**Comment by nikogu** [comment]
ReactDOM 的依赖源自于 `ssr`，去掉是可以的
