### ISSUE TITLE
【业务组件】GlobalFooter 页脚

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/test#9]
<img width="903" alt="2017-07-20 2 59 10" src="https://user-images.githubusercontent.com/7017767/28406632-ee8c136c-6d63-11e7-9fc0-6cfbdb33ee0a.png">

[视觉稿](https://lark.alipay.com/ui-assets/bf3zoa/44366)

**使用方式**

```
<GlobalFooter
  data={{
    links: [
        {
          title: '帮助',
          href: 'http://xxxxxx',
        }
    ],
    copyright: '2017 蚂蚁金服xxxxx'
  }}
/>
```

**功能概要**

- 静态容器，会对内容的颜色，大小，对齐方式等进行定制

**API**

| 参数        | 说明        | 类型        | 默认值 |
|----------- |------------ | ---------- |-------|
| style       | 样式   | object     | -    |
| data       | 数据   | object     | -    |

**Comment by nikogu** [comment]
这个建议配 `data`

```
<Footer
  data={{
    links: [
        {
          title: '帮助',
          href: 'http://xxxxxx',
        }
    ],
    copyright: '2017 蚂蚁金服xxxxx'
  }}
/>
```

**Comment by ddcat1115** [comment]
我确定一下是否footer只可能是link+copyright...

**Comment by ddcat1115** [comment]
已更新

**Comment by afc163** [comment]
PageFooter

**Comment by ddcat1115** [comment]
https://github.com/ant-design/test/pull/29
